services:
  - type: web
    name: ttrpg-finder
    env: docker
    dockerComposePath: docker-compose.yml
    plan: free
    buildCommand: ""
    startCommand: docker-compose up
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod